import Header1 from "./Header1";
import Header2 from "./Header2.js";
import Header3 from "./Header3.js";
import HeaderSm from "./HeaderSm.js";
import Section1 from "./Section1";
import Section2 from "./Section2";
import Section3 from "./Section3";
import Section4 from "./Section4";
import Section4Mobile from "./Section4Mobile";
import Section5 from "./Section5";
import Section6 from "./Section6";
import Section7 from "./Section7";
import Section8 from "./Section8";
import Section9 from "./Section9";
import Section10 from "./Section10";
import Section11 from "./Section11";
import Section12 from "./Section12.js";
import Section13 from "./Section13.js";
import Section14 from "./Section14.js";
import Section15 from "./Section15.js";
import Section16 from "./Section16.js";
import Section17 from "./Section17";
import Footer1 from "./Footer1";
import Footer2 from "./Footer2";
import Footer3 from "./Footer3";
import Footer4 from "./Footer4";
import Footer5 from "./Footer5";
import Footer6 from "./Footer6";
import Footer7 from "./Footer7";
import Footer8 from "./Footer8";

Header1();
Header2();
Header3();
HeaderSm();
Section1();
Section2();
Section3();
Section4();
Section4Mobile();
Section5();
Section6();
Section7();
Section8();
Section9();
Section10();
Section11();
Section12();
Section13();
Section14();
Section15();
Section16();
Section17();
Footer1();
Footer2();
Footer3();
Footer4();
Footer5();
Footer6();
Footer7();
Footer8();
